### ISSUE TITLE
toiveita

### ISSUE THREAD

**Issue by ertsi** [pelilegacy/autoretku#2]
- muista minut
- multi-account tuki (liittyy edelliseen)
käytännössä tallentaa login infot (joku perus dropdown tms?)

**Comment by nikoheikkila** [comment]
![image](https://cloud.githubusercontent.com/assets/457034/6769149/172d4162-d098-11e4-8ab7-3de26faf5346.jpg)

**Comment by Arkkis** [comment]
Fix'd
